export enum DisabilityType {
  DYSLEXIA = 'DYSLEXIA',

  DYSCALCULIA = 'DYSCALCULIA',

  DYSGRAPHIA = 'DYSGRAPHIA',

  ADHD = 'ADHD',

  APD = 'APD',

  VISUAL_PROCESSING = 'VISUAL_PROCESSING',

  LANGUAGE_PROCESSING = 'LANGUAGE_PROCESSING',
}
